### PR TITLE
Feature/1.7.0 changes

### PR DESCRIPTION
**Pull request by infeo**
This branch requires changes for the upcoming 1.7.0 version.

It includes an update of libfuse to version 3 and the activation of aarch64 builds.

This branch should only be merged, once 1.7.0 is finally released.

### CODE REVIEW

**Comment by purejava** [comment]
Hi,

I think you need `org.freedesktop.Platform` runtime version `22.08.6` for `libfuse 3.13.0`. See the [release notes](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases).

Even if I add flathub-beta as a remote, the newest version I can get is `22.08.5`. It doesn't seem to be released yet.
```sh
ralph@fusion flathub % flatpak search org.freedesktop.Platform | grep Shared
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	22.08rc.3	22.08beta	flathub-beta
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	21.08rc.4	21.08beta	flathub-beta
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	20.08rc.2	20.08beta	flathub-beta
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	19.08beta.9	19.08beta	flathub-beta
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	22.08.5	22.08	flathub
Freedesktop Platform	Shared libraries	org.freedesktop.Platform	21.08.17.1	21.08	flathub
```

Kind regards

**Comment by purejava** [comment]
`22.08beta` is older than `22.08.6` too:
```sh
ralph@fusion ~ % flatpak info org.freedesktop.Platform/x86_64/22.08beta

Freedesktop Platform - Shared libraries

     Kennung: org.freedesktop.Platform
         Ref: runtime/org.freedesktop.Platform/x86_64/22.08beta
 Architektur: x86_64
       Zweig: 22.08beta
     Version: 22.08rc.3
      Lizenz: MIT
    Ursprung: flathub-beta
    Sammlung: org.flathub.Beta
Installation: system
 Installiert: 573,4 MB

      Commit: 0390299e631b68d97a38b7eabc7527d27713fb28313f402c80a5a4095ea8164f
      Parent: 01f961fd102be01ebdfe8d7f3ed94661beebb15450d6361f150baf2e2c81c285
     Betreff: Export org.freedesktop.Platform
       Datum: 2022-08-26 15:33:02 +0000
ralph@fusion ~ %
```

**Comment by purejava** [comment]
Unfortunately, the `Error: module libfuse: Can't find autogen, autogen.sh or bootstrap` is still there with a newer runtime and a matching version of libfuse:
```diff
diff --git a/org.cryptomator.Cryptomator.yaml b/org.cryptomator.Cryptomator.yaml
index 6fc5a95..45ec534 100644
--- a/org.cryptomator.Cryptomator.yaml
+++ b/org.cryptomator.Cryptomator.yaml
@@ -1,7 +1,7 @@
 app-id: org.cryptomator.Cryptomator
 command: cryptomator
 runtime: org.freedesktop.Platform
-runtime-version: '21.08'
+runtime-version: '22.08'
 sdk: org.freedesktop.Sdk
 separate-locales: false
 finish-args:
@@ -30,8 +30,8 @@ modules:
       - install fusermount-wrapper.sh /app/bin/fusermount
     sources:
       - type: archive
-        url: https://github.com/libfuse/libfuse/releases/download/fuse-3.13.0/fuse-3.13.0.tar.xz
-        sha256: 1e54d3ee1d7d04f41e77617c4f7514f611b94332215dd88394bd82803032752a
+        url: https://github.com/libfuse/libfuse/releases/download/fuse-3.12.0/fuse-3.12.0.tar.xz
+        sha256: 33b8a92d6f7a88e6a889f0009206933482f48f3eb85d88cf09ef551313ac7373
       - type: file
         path: build-aux/fusermount-wrapper.sh
   - name: cryptomator
```
This must be something different.

**Comment by purejava** [comment]
> Unfortunately, the `Error: module libfuse: Can't find autogen, autogen.sh or bootstrap` is still there with a newer runtime and a matching version of libfuse.
> This must be something different.

The magic that needs to be added here is to change the build system to meson. It builds fine then with the latest libfuse.

Please note, that a further command wrapper has been added: `umount-wrapper.sh`. This should be fine. I checked the code of `fuse-nio-adapter`. It uses the commands `fusermount` and `umount`.

**Comment by overheadhunter** [comment]
> Please note, that a further command wrapper has been added: umount-wrapper.sh. This should be fine. I checked the code of fuse-nio-adapter. It uses the commands fusermount and umount.

Just for the record: as @purejava noted in the linked PR, this is no longer the case. We use `fusermount -u` for unmounting.

**Comment by infeo** [comment]
The aarch64 build fails due to:
```
Could not transfer artifact org.openjfx:javafx-base:jar:linux-aarch64:19 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/19/javafx-base-19-linux-aarch64.jar: Unknown host repo.maven.apache.org -> [Help 1]
```

@SailReal Can we retry the build?

**Comment by SailReal** [comment]
> @SailReal Can we retry the build?

We need to add those `aarch64` libs to the https://github.com/flathub/org.cryptomator.Cryptomator/blob/master/maven-dependencies.yaml. Maybe it's time to automate the required steps for updates, especially since we now have to do it on two different architectures.

**Comment by purejava** [comment]
I run the build for `x86_64` to check that libfuse3 is working and got the following UnsatisfiedLinkError on mounting:
```java
Error Code KTBV:VT87:VT87
java.lang.UnsatisfiedLinkError: libfuse.so.2: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Library names
[libfuse.so.2]
Search paths:
[, /app/Cryptomator/lib/app, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib, /usr/local/lib, /app/lib]
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:111)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:85)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:64)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:74)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:138)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:86)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:399)
	at ru.serce.jnrfuse.AbstractFuseFS.<init>(AbstractFuseFS.java:77)
	at ru.serce.jnrfuse.FuseStubFS.<init>(FuseStubFS.java:23)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.ReadOnlyAdapter.<init>(ReadOnlyAdapter.java:68)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.ReadWriteAdapter.<init>(ReadWriteAdapter.java:55)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.ReadWriteAdapter_Factory.newInstance(ReadWriteAdapter_Factory.java:86)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.ReadWriteAdapter_Factory.get(ReadWriteAdapter_Factory.java:67)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.ReadWriteAdapter_Factory.get(ReadWriteAdapter_Factory.java:11)
	at dagger@2.44/dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.DaggerFuseNioAdapterComponent.readWriteAdapter(DaggerFuseNioAdapterComponent.java:98)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.AdapterFactory.createReadWriteAdapter(AdapterFactory.java:59)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.mount.AbstractMounter.mount(AbstractMounter.java:20)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.mount.Mounter.mount(Mounter.java:15)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.common.vaults.FuseVolume.mount(FuseVolume.java:53)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.common.vaults.FuseVolume.mount(FuseVolume.java:42)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.common.vaults.Vault.unlock(Vault.java:154)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.ui.unlock.UnlockWorkflow.attemptUnlock(UnlockWorkflow.java:72)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:62)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:35)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I looks as if jnr-fuse is bound to `libfuse2`:
```java
libFuse = LibraryLoader.create(LibFuse.class).failImmediately().load("libfuse.so.2");
```
https://github.com/SerCeMan/jnr-fuse/blob/c4dfaef01a9a3156f8764cf2837950a95f31bfdc/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java#L77

**Comment by infeo** [comment]
> I run the build for x86_64 to check that libfuse3 is working and got the following UnsatisfiedLinkError on mounting:

That is actually expected 😅 This will only resolve when Cryptomator 1.7.0 is published,where the jnr dependency is dropped (also with libfuse2). You can test it with the current beta, then it should work.

**Comment by purejava** [comment]
> That is actually expected 😅 This will only resolve when Cryptomator 1.7.0 is published,where the jnr dependency is dropped (also with libfuse2). You can test it with the current beta, then it should work.

Nice! I've noticed `cryptomator/jfuse` and that it's using JEP 424, but wasn't aware that it also introduces libfuse3.

I'll give the current beta a whirl with flatpak-builder build.

**Comment by SailReal** [comment]
With https://github.com/flathub/org.cryptomator.Cryptomator/pull/22/commits/4bfbd03216092d994ebd1b89d56bb2dafd30c5a0 and the fixes https://github.com/cryptomator/fuse-nio-adapter/commit/9f83db25e52af41b388ca9fb306c691ce70e8ff7 and https://github.com/cryptomator/fuse-nio-adapter/commit/6441c200842559a5b547c80944ba4d349b23040b I was able to unlock/lock a vault using the 1.7.0 and Fuse on `x86_64`.

Will test it using `aarch64` as well as soon as we have beta2 out with the fixes in the `fuse-nio-adapter`.

**Comment by SailReal** [comment]
After using it for some days in production, I noticed that `Locate Encrypted File` doesn't work `WARN  o.c.u.m.VaultDetailUnlockedController - No service provider to reveal files found.`

 ...let's see what the problem here is.

**Comment by infeo** [comment]
> ...let's see what the problem here is.

The linux implemenation of RevealPath uses the system command `dbus-send` and uses the [freedesktop filemanager](https://freedesktop.org/wiki/Specifications/file-manager-interface/) interface.

**Comment by SailReal** [comment]
Adding `talk-name=org.freedesktop.FileManager1` to the `finish-args` helps to open a file/folder from within a shell in the flatpak sandbox using `flatpak run --command=sh org.cryptomator.Cryptomator` and `dbus-send --print-reply --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:"file:///home/julian/foo.txt" string:`. But I think revealing still fails because of we are checking if `dbus-send` exists and (`nautilus` or `dolphin`) in

https://github.com/cryptomator/integrations-linux/blob/cc65fd9dd2b58cf92f0f00cb896d8d1513dadff1/src/main/java/org/cryptomator/linux/revealpath/DBusFileMangerRevealPath.java#L61-L62

Currently only `dbus-send` is available in `/app/bin/:/usr/bin/`. I'm not quite sure how we can solve the problem, I'll have to do some research.

**Comment by infeo** [comment]
One way is to search the DBus for implementations of the filemanager interface. Problem is, that this could take some time and requires complete access to the session bus.

**Comment by SailReal** [comment]
Tested it again using https://github.com/cryptomator/integrations-linux/pull/17#pullrequestreview-1291213553. IMO it now works as expected :tada: :clinking_glasses: 

Looking forward to Beta3 or will this already be an RC?

**Comment by SailReal** [comment]
https://dl.flathub.org/build-repo/5782/org.cryptomator.Cryptomator.flatpakref looks good to me on `x86_64`.

Let's see what `aarch64` has to say about this build.

**Comment by infeo** [comment]
1.7.0 is out now, in https://github.com/flathub/org.cryptomator.Cryptomator/pull/22/commits/993cef1f360f8d64642583e2757af52fdd86ecd9 i updated to it.

@SailReal Can you make a last review?

**Review by SailReal — APPROVED** [review]
LGTM :+1:

**Pull request merged**
