### PR TITLE
Release 1.10.0

### PR DESCRIPTION
**Pull request by infeo**
TODO before merge: #39

### CODE REVIEW

**Comment by SailReal** [comment]
After merging #39, we should set `--java-options '-Dcryptomator.showTrayIcon=true'`, right?

**Comment by purejava** [comment]
> After merging #39, we should set `--java-options '-Dcryptomator.showTrayIcon=true'`, right?

Basically, yes. #39 will enable the new tray icon functionality for the flatpak-ed app, but it currently falls back to AWT, due to [a needed improvement](https://github.com/flathub/org.cryptomator.Cryptomator/issues/50) of the Java bindings.

I am working on a new release of the Java bindings anyway, as I am [making them compile with Java 21](https://github.com/purejava/appindicator-gtk3-java/issues/14) and plan to release it within the next couple of days, so it depends on your plans for Cryptomator, whether to set  `--java-options '-Dcryptomator.showTrayIcon=true'` for the flatpak-ed app.
As you know, the flatpak-ed app depends on Cryptomator releases, which embed the Java bindings. Unless a new Cryptomator release is published, including the new release of the Java bindings, that can be the base for the flatpak-ed app, the tray icon functionality won't work.

So you might consider to keep `--java-options '-Dcryptomator.showTrayIcon=false'`, until all this is fixed.

**Comment by infeo** [comment]
> So you might consider to keep --java-options '-Dcryptomator.showTrayIcon=false', until all this is fixed.

Yes, that will be the solution for now.

>as I am https://github.com/purejava/appindicator-gtk3-java/issues/14 and plan to release it within the next couple of days

We cannot integrate any library using JDK 21 and preview features, because the early access flag can only "target" one JDK. Therefore, as unfortunate as it is, appindicator cannot be used until the next feature release of Cryptomator.

**Comment by purejava** [comment]
> We cannot integrate any library using JDK 21 and preview features, because the early access flag can only "target" one JDK. Therefore, as unfortunate as it is, appindicator cannot be used until the next feature release of Cryptomator.

Oh, yeah. You are right. Would it help, when I keep the bindings based on Java 20 and release a new version containing the fix making it compatible with flatpak very soon and continue working on the Java 21 release afterwards?

**Comment by infeo** [comment]
> Would it help, when I keep the bindings based on Java 20 and release a new version containing the fix making it compatible with flatpak very soon and continue working on the Java 21 release afterwards?

Yes.

**Comment by infeo** [comment]
> keep the bindings based on Java 20 and release a new version containing the fix making it compatible with flatpak 

This will be fixed an a patch release of Cryptomator. @purejava Notify us, when the new version of libappindicator is released.

**Comment by purejava** [comment]
@infeo This issue should be fixed with [appindicator-gtk3-java release 1.3.4.](https://github.com/purejava/appindicator-gtk3-java/releases/tag/1.3.4).

I'll need to build `integrations-linux`, containing the new release, locally and afterwards build the flatpaked Cryptomator to test it.

**Comment by purejava** [comment]
Fixed with appindicator-gtk3-java release `1.3.4`. See [here](https://github.com/flathub/org.cryptomator.Cryptomator/issues/50#issuecomment-1719896668).

**Pull request merged**
