### PR TITLE
Provide SVG_SOURCE_PROPERTY

### PR DESCRIPTION
**Pull request by purejava**
Fixes https://github.com/cryptomator/cryptomator/issues/3315

### CODE REVIEW

**Comment by SailReal** [comment]
Thanks for looking into it, we did check the reason for it yesterday and need to change this if condition back https://github.com/cryptomator/integrations-linux/blob/8d993facac02f53cf5f66b0028250ad9061f20fa/src/main/java/org/cryptomator/linux/tray/AppindicatorTrayMenuController.java#L52, it needs to be something like `if (svgSourcePath == null)` again but yes, as we copy it to `@{appdir}/usr/share/icons/hicolor/symbolic/apps` we could also load it from there (the same applies to AUR) :thinking:

**Comment by infeo** [comment]
@purejava Is this change useful even after fixing the actual problem in integrations-linux? I.e. does it make sense to specify the path?

**Comment by purejava** [comment]
Hi @infeo, no.

I wasn't aware of this change: https://github.com/cryptomator/integrations-linux/commit/0f6a4260b6de8a1a968398e2c8de9805257f7dfe

The "if" needs to be reverted. And  please consider this: https://github.com/cryptomator/cryptomator/pull/2885#issuecomment-1567123907

`appdir` is set and not set for AppImage and ppa.

HTH

**Comment by purejava** [comment]
The last part of my comment above is relevant if you change icon loading from paths on different platforms.

**Comment by infeo** [comment]
> relevant if you change icon loading from paths on different platforms

Since we are changing nothing and only reestablish the former state, i'm closing this PR. Nonentheless, thanks for your quick reaction, @purejava!

**Pull request closed without merging**
